### ISSUE TITLE
Checkboxes when blocking a specific cookies do not work

### ISSUE THREAD

**Issue by mgrottenthaler** [ETCExtensions/Edit-This-Cookie#223]
When blocking a specific cookie over the UI you get these 3 checkboxes: block by domain, name and value. Unchecking them does not work. After blocking a cookie like this, the blocked cookie entry still shows all the values instead of "any".

It's also not possible to edit blocked cookie entries. It would be nice to edit entries to easier fix this problem. Also copy & paste would be nice.

**Comment by Agent1101** [comment]
@mgrottenthaler @fcapano 
Hi,
there is incorrect comparison in `popup.js` at lines 355,357,359.

https://github.com/ETCExtensions/Edit-This-Cookie/blob/f44060da2e7b2a425b27f53dc403cbeb42abbd10/js/popup.js#L355-L360

it must be compared with `undefined`. because the values will never be `null`. I changed like following and works ;-)

`355:    var domainChecked = $(".filterDomain:checked", $(this).parent()).val() !== undefined;`
`257:    var nameChecked = $(".filterName:checked", $(this).parent()).val() !== undefined;`
`359:    var valueChecked = $(".filterValue:checked", $(this).parent()).val() !== undefined;`
